name: Deploy Ecommerce API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish WebAPI
        run: dotnet publish ./Ecommerce.WebAPI/Ecommerce.WebAPI.csproj --configuration Release

      - name: Verify publish directory
        run: |
          echo "Checking if publish folder exists..."
          if [ -d "./Ecommerce.WebAPI/bin/Release/net9.0/publish" ]; then
            echo "✅ Publish folder found."
            ls -la ./Ecommerce.WebAPI/bin/Release/net9.0/publish
          else
            echo "❌ Publish folder missing."
            exit 1
          fi

      - name: Zip publish folder
        run: |
          cd ./Ecommerce.WebAPI/bin/Release/net9.0
          zip -r publish.zip ./publish

      - name: Run tests
        run: dotnet test ./Ecommerce.Tests/Ecommerce.Tests.csproj --configuration Release --verbosity detailed

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy using ZIP
        run: |
          az webapp deployment source config-zip \
            --name Ecommerce-webapi \
            --resource-group BackendDev-EU-RG \
            --src ./Ecommerce.WebAPI/bin/Release/net9.0/publish.zip
